// SolutionExport.jsx — the whole worked solution on one printable page.
import { Set, Fd, SetList, Empty } from './atoms.jsx';
import { fmt, fmtFd } from '../logic/setOps.js';

function plainText(a) {
  const L = [];
  L.push('NORMALIZATION VIRTUAL LAB — WORKED SOLUTION');
  L.push('='.repeat(60));
  L.push(`Relation:  R(${a.parsed.attributes.join(', ')})`);
  L.push(`Functional dependencies:  ${a.parsed.fds.map(fmtFd).join(';  ') || 'none'}`);
  if (a.parsed.mvds.length) L.push(`Multivalued dependencies:  ${a.parsed.mvds.map(fmtFd).join(';  ')}`);
  if (a.parsed.jds.length)
    L.push(`Join dependencies:  ${a.parsed.jds.map((j) => `*(${j.components.map(fmt).join(', ')})`).join(';  ')}`);
  L.push('');
  L.push('1. KEYS');
  L.push(`   Candidate keys:  ${a.keys.candidateKeys.map(fmt).join(', ')}`);
  L.push(`   Prime:           ${fmt(a.keys.primeAttributes)}`);
  L.push(`   Non-prime:       ${fmt(a.keys.nonPrimeAttributes) || '(none)'}`);
  L.push(`   Superkeys:       ${a.keys.superKeys.length}`);
  L.push('');
  L.push('2. MINIMAL COVER');
  L.push(`   ${a.minimalCover.cover.map(fmtFd).join(';  ') || '(empty)'}`);
  a.minimalCover.steps.forEach((s, i) => L.push(`   ${i + 1}. ${s.reason}`));
  L.push('');
  L.push('3. NORMAL FORM');
  L.push(`   Highest normal form satisfied: ${a.normalForm.highestNF}`);
  a.normalForm.checks.forEach((c) =>
    L.push(`   ${c.nf.padEnd(5)} ${c.assumed ? 'assumed' : c.passed ? 'pass' : 'FAIL'}  — ${c.note}`)
  );
  a.normalForm.violations.forEach((v) => L.push(`   ! ${fmtFd(v.fd)} — ${v.reason}`));
  L.push('');
  L.push('4. 3NF DECOMPOSITION (synthesis)');
  a.decomposition.three.relations.forEach((r) =>
    L.push(`   ${r.name}(${r.attributes.join(', ')})  key ${r.candidateKeys.map(fmt).join(' / ')}  [${r.highestNF}]`)
  );
  L.push(`   Lossless: ${a.decomposition.three.lossless ? 'yes' : 'no'}   Dependency preserving: ${a.decomposition.three.dependencyPreserving ? 'yes' : 'no'}`);
  L.push('');
  L.push('5. BCNF DECOMPOSITION (analysis)');
  a.decomposition.bcnf.relations.forEach((r) =>
    L.push(`   ${r.name}(${r.attributes.join(', ')})  key ${r.candidateKeys.map(fmt).join(' / ')}  [${r.highestNF}]`)
  );
  L.push(`   Lossless: ${a.decomposition.bcnf.lossless ? 'yes' : 'no'}   Dependency preserving: ${a.decomposition.bcnf.dependencyPreserving ? 'yes' : 'no'}`);
  if (a.decomposition.bcnf.dependencyDetail.lostFds.length)
    L.push(`   Lost: ${a.decomposition.bcnf.dependencyDetail.lostFds.map(fmtFd).join(', ')}`);
  L.push('');
  if (a.parsed.mvds.length) {
    L.push('6. 4NF');
    L.push(`   In 4NF: ${a.higher.four.is4NF ? 'yes' : 'no'}`);
    a.higher.four.violations.forEach((v) => L.push(`   ! ${fmtFd(v.dependency)} — ${v.reason}`));
    if (a.higher.four_decomp?.relations.length)
      L.push(`   Decomposition: ${a.higher.four_decomp.relations.map((r) => `(${r.attributes.join(', ')})`).join('  ')}`);
    L.push('');
  }
  if (a.parsed.jds.length && a.higher.five) {
    L.push('7. 5NF CHECK (scoped)');
    L.push(`   ${a.higher.five.reason}`);
    L.push('');
  }
  L.push('-'.repeat(60));
  L.push('Generated by the Normalization Virtual Lab.');
  return L.join('\n');
}

export default function SolutionExport({ analysis }) {
  if (!analysis) {
    return <Empty title="Nothing analysed yet">Define a relation on the Input tab and press Analyse.</Empty>;
  }
  const a = analysis;
  const text = plainText(a);

  const copy = () => navigator.clipboard?.writeText(text);

  return (
    <>
      <div className="card no-print">
        <h2>Export the worked solution</h2>
        <p className="sub">
          Everything the lab computed for this relation, on one page. Print it, save it as a PDF from the
          print dialog, or copy the plain-text version straight into a report.
        </p>
        <div className="btn-row">
          <button className="btn" onClick={() => window.print()}>Print / save as PDF</button>
          <button className="btn ghost" onClick={copy}>Copy as plain text</button>
        </div>
      </div>

      <div className="card">
        <h2>R({a.parsed.attributes.join(', ')})</h2>
        <p className="sub">
          {a.parsed.fds.length} functional dependenc{a.parsed.fds.length === 1 ? 'y' : 'ies'}
          {a.parsed.mvds.length ? `, ${a.parsed.mvds.length} multivalued` : ''}
          {a.parsed.jds.length ? `, ${a.parsed.jds.length} join dependency` : ''} · highest normal form{' '}
          <b>{a.normalForm.highestNF}</b>
        </p>

        <h3>Given</h3>
        <div className="set-list">{a.parsed.fds.map((f, i) => <Fd key={i} of={f} />)}</div>
        {a.parsed.mvds.length > 0 && (
          <div className="set-list" style={{ marginTop: 8 }}>
            {a.parsed.mvds.map((f, i) => <Fd key={i} of={f} />)}
          </div>
        )}

        <h3>1 · Keys</h3>
        <table className="data">
          <tbody>
            <tr><th style={{ width: 190 }}>Candidate keys</th><td><SetList items={a.keys.candidateKeys} tone="key" /></td></tr>
            <tr><th>Prime</th><td><Set of={a.keys.primeAttributes} tone="key" /></td></tr>
            <tr><th>Non-prime</th><td>{a.keys.nonPrimeAttributes.length ? <Set of={a.keys.nonPrimeAttributes} /> : <span className="muted">none</span>}</td></tr>
          </tbody>
        </table>

        <h3>2 · Minimal cover</h3>
        <div className="set-list">
          {a.minimalCover.cover.length
            ? a.minimalCover.cover.map((f, i) => <Fd key={i} of={f} />)
            : <span className="muted">empty</span>}
        </div>

        <h3>3 · Normal form</h3>
        <div className="ladder">
          {a.normalForm.checks.map((c) => (
            <div key={c.nf} className={`rung ${c.assumed ? 'assumed' : c.passed ? 'pass' : 'fail'}`}>
              <div className="nf">{c.nf}</div>
              <div className="mark">{c.assumed ? '≈' : c.passed ? '✓' : '✗'}</div>
              <div className="note">{c.note}</div>
            </div>
          ))}
        </div>

        <h3>4 · Decompositions</h3>
        <div className="tbl-wrap">
          <table className="data">
            <thead>
              <tr><th>algorithm</th><th>resulting schema</th><th>lossless</th><th>dependency preserving</th></tr>
            </thead>
            <tbody>
              <tr>
                <td>3NF synthesis</td>
                <td className="mono">{a.decomposition.three.relations.map((r) => `(${r.attributes.join(',')})`).join('  ')}</td>
                <td>{a.decomposition.three.lossless ? 'yes' : 'no'}</td>
                <td>{a.decomposition.three.dependencyPreserving ? 'yes' : 'no'}</td>
              </tr>
              <tr>
                <td>BCNF analysis</td>
                <td className="mono">{a.decomposition.bcnf.relations.map((r) => `(${r.attributes.join(',')})`).join('  ')}</td>
                <td>{a.decomposition.bcnf.lossless ? 'yes' : 'no'}</td>
                <td>{a.decomposition.bcnf.dependencyPreserving ? 'yes' : 'no'}</td>
              </tr>
            </tbody>
          </table>
        </div>

        {a.parsed.mvds.length > 0 && (
          <>
            <h3>5 · 4NF</h3>
            <p>{a.higher.four.is4NF ? 'In 4NF.' : 'Not in 4NF.'}{' '}
              {a.higher.four.violations.map((v, i) => <span key={i}>{fmtFd(v.dependency)} — {v.reason} </span>)}
            </p>
          </>
        )}

        {a.parsed.jds.length > 0 && a.higher.five && (
          <>
            <h3>6 · 5NF check</h3>
            <p>{a.higher.five.reason}</p>
            <p className="muted">{a.higher.five.scope}</p>
          </>
        )}
      </div>

      <div className="card no-print">
        <h2>Plain text</h2>
        <pre className="qgiven" style={{ whiteSpace: 'pre-wrap', maxHeight: 380, overflow: 'auto' }}>{text}</pre>
      </div>
    </>
  );
}
